CREATE DATABASE dashcode;
USE dashcode;

CREATE TABLE USERS (ID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(90) NOT NULL);
CREATE TABLE LOGIN (ID INTEGER NOT NULL, EMAIL VARCHAR(90) PRIMARY KEY NOT NULL, PASSWORD VARCHAR(100) NOT NULL, FOREIGN KEY(ID) REFERENCES USERS(ID));
